In [1]:
#Import libraries, packages with import
#This tool support the cleaning and preparation of the UNR IDD Dataset
import pandas as pd

In [2]:
#Import CSV Dataset (UNR-IDD) with network traffic
df = pd.read_csv("/Users/sinaronke/Desktop/Neues Datenset/UNR-IDD.csv")
df.head()

,Switch ID,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Rx Dropped,Packets Tx Dropped,Packets Rx Errors,...,Unknown Load/Latest,Latest bytes counter,is_valid,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Max Size,Label,Binary Label
0,of:000000000000000c,Port#:1,132,9181,6311853,238,46,0,0,0,...,0,0,True,0,9,767,688,-1,TCP-SYN,Attack
1,of:000000000000000c,Port#:2,187,6304498,15713,171,46,0,0,0,...,0,0,True,0,9,767,688,-1,TCP-SYN,Attack
2,of:000000000000000c,Port#:3,235,6311567,8030,58,46,0,0,0,...,0,0,True,0,9,767,688,-1,TCP-SYN,Attack
3,of:000000000000000c,Port#:4,59,7878,16439,182,46,0,0,0,...,0,0,True,0,9,767,688,-1,TCP-SYN,Attack
4,of:000000000000000a,Port#:1,188,6304547,16497,183,46,0,0,0,...,0,0,True,0,7,489,403,-1,TCP-SYN,Attack

In [3]:
# Information about rows (37.411) & columns (features 34)
df.shape

(37411, 34)

In [4]:
# check if all Datasets have 37411 values
df.count()

Switch ID                        37411
Port Number                      37411
Received Packets                 37411
Received Bytes                   37411
Sent Bytes                       37411
Sent Packets                     37411
Port alive Duration (S)          37411
Packets Rx Dropped               37411
Packets Tx Dropped               37411
Packets Rx Errors                37411
Packets Tx Errors                37411
Delta Received Packets           37411
Delta Received Bytes             37411
Delta Sent Bytes                 37411
Delta Sent Packets               37411
Delta Port alive Duration (S)    37411
Delta Packets Rx Dropped         37411
 Delta Packets Tx Dropped        37411
Delta Packets Rx Errors          37411
Delta Packets Tx Errors          37411
Connection Point                 37411
Total Load/Rate                  37411
Total Load/Latest                37411
Unknown Load/Rate                37411
Unknown Load/Latest              37411
Latest bytes counter             37411
is_valid                         37411
Table ID                         37411
Active Flow Entries              37411
Packets Looked Up                37411
Packets Matched                  37411
Max Size                         37411
Label                            37411
Binary Label                     37411
dtype: int64

In [5]:
#Are there duplicated raws in the Dataset?
df[df.duplicated(keep=False)]

,Switch ID,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Rx Dropped,Packets Tx Dropped,Packets Rx Errors,...,Unknown Load/Latest,Latest bytes counter,is_valid,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Max Size,Label,Binary Label
31223,of:000000000000000a,Port#:3,66,9078,8992,63,56,0,0,0,...,0,0,True,0,4,201,123,-1,PortScan,Attack
32287,of:000000000000000a,Port#:3,66,9078,8992,63,56,0,0,0,...,0,0,True,0,4,201,123,-1,PortScan,Attack

In [6]:
#Check if values missing
df.isnull().sum()

Switch ID                        0
Port Number                      0
Received Packets                 0
Received Bytes                   0
Sent Bytes                       0
Sent Packets                     0
Port alive Duration (S)          0
Packets Rx Dropped               0
Packets Tx Dropped               0
Packets Rx Errors                0
Packets Tx Errors                0
Delta Received Packets           0
Delta Received Bytes             0
Delta Sent Bytes                 0
Delta Sent Packets               0
Delta Port alive Duration (S)    0
Delta Packets Rx Dropped         0
 Delta Packets Tx Dropped        0
Delta Packets Rx Errors          0
Delta Packets Tx Errors          0
Connection Point                 0
Total Load/Rate                  0
Total Load/Latest                0
Unknown Load/Rate                0
Unknown Load/Latest              0
Latest bytes counter             0
is_valid                         0
Table ID                         0
Active Flow Entries              0
Packets Looked Up                0
Packets Matched                  0
Max Size                         0
Label                            0
Binary Label                     0
dtype: int64

In [7]:
#Delete the space in front of "Delta Packtes Tx Dropped" / and all other spaces before and after 
df.columns = df.columns.str.lstrip()
df.columns = df.columns.str.rstrip()

In [8]:
#Datatypes
df.dtypes

Switch ID                        object
Port Number                      object
Received Packets                  int64
Received Bytes                    int64
Sent Bytes                        int64
Sent Packets                      int64
Port alive Duration (S)           int64
Packets Rx Dropped                int64
Packets Tx Dropped                int64
Packets Rx Errors                 int64
Packets Tx Errors                 int64
Delta Received Packets            int64
Delta Received Bytes              int64
Delta Sent Bytes                  int64
Delta Sent Packets                int64
Delta Port alive Duration (S)     int64
Delta Packets Rx Dropped          int64
Delta Packets Tx Dropped          int64
Delta Packets Rx Errors           int64
Delta Packets Tx Errors           int64
Connection Point                  int64
Total Load/Rate                   int64
Total Load/Latest                 int64
Unknown Load/Rate                 int64
Unknown Load/Latest               int64
Latest bytes counter              int64
is_valid                           bool
Table ID                          int64
Active Flow Entries               int64
Packets Looked Up                 int64
Packets Matched                   int64
Max Size                          int64
Label                            object
Binary Label                     object
dtype: object

In [9]:
#Check if "is_valid" only true contained
df.groupby("is_valid").count()

,Switch ID,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Rx Dropped,Packets Tx Dropped,Packets Rx Errors,...,Unknown Load/Rate,Unknown Load/Latest,Latest bytes counter,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Max Size,Label,Binary Label
is_valid,,,,,,,,,,,,,,,,,,,,,
True,37411,37411,37411,37411,37411,37411,37411,37411,37411,37411,...,37411,37411,37411,37411,37411,37411,37411,37411,37411,37411

In [10]:
#Check which values in Max Size
df.groupby("Max Size").count()

,Switch ID,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Rx Dropped,Packets Tx Dropped,Packets Rx Errors,...,Unknown Load/Rate,Unknown Load/Latest,Latest bytes counter,is_valid,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Label,Binary Label
Max Size,,,,,,,,,,,,,,,,,,,,,
-1,37411,37411,37411,37411,37411,37411,37411,37411,37411,37411,...,37411,37411,37411,37411,37411,37411,37411,37411,37411,37411

In [11]:
df.groupby("Packets Rx Dropped").count()

,Switch ID,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Tx Dropped,Packets Rx Errors,Packets Tx Errors,...,Unknown Load/Latest,Latest bytes counter,is_valid,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Max Size,Label,Binary Label
Packets Rx Dropped,,,,,,,,,,,,,,,,,,,,,
0,37411,37411,37411,37411,37411,37411,37411,37411,37411,37411,...,37411,37411,37411,37411,37411,37411,37411,37411,37411,37411

In [12]:
#Delete is_valid, Max Size, Packets Rx Dropped
df = df.drop("is_valid", axis=1)
df = df.drop("Max Size", axis=1)
df = df.drop("Packets Rx Dropped", axis=1)

In [13]:
df["Binary Label"].value_counts(dropna=False)

Attack    33638
Normal     3773
Name: Binary Label, dtype: int64

In [14]:
df.groupby("Switch ID").count()

,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Tx Dropped,Packets Rx Errors,Packets Tx Errors,Delta Received Packets,...,Total Load/Latest,Unknown Load/Rate,Unknown Load/Latest,Latest bytes counter,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Label,Binary Label
Switch ID,,,,,,,,,,,,,,,,,,,,,
of:0000000000000001,3780,3780,3780,3780,3780,3780,3780,3780,3780,3780,...,3780,3780,3780,3780,3780,3780,3780,3780,3780,3780
of:0000000000000002,1884,1884,1884,1884,1884,1884,1884,1884,1884,1884,...,1884,1884,1884,1884,1884,1884,1884,1884,1884,1884
of:0000000000000003,4910,4910,4910,4910,4910,4910,4910,4910,4910,4910,...,4910,4910,4910,4910,4910,4910,4910,4910,4910,4910
of:0000000000000004,3386,3386,3386,3386,3386,3386,3386,3386,3386,3386,...,3386,3386,3386,3386,3386,3386,3386,3386,3386,3386
of:0000000000000005,2056,2056,2056,2056,2056,2056,2056,2056,2056,2056,...,2056,2056,2056,2056,2056,2056,2056,2056,2056,2056
of:0000000000000006,1752,1752,1752,1752,1752,1752,1752,1752,1752,1752,...,1752,1752,1752,1752,1752,1752,1752,1752,1752,1752
of:0000000000000007,2620,2620,2620,2620,2620,2620,2620,2620,2620,2620,...,2620,2620,2620,2620,2620,2620,2620,2620,2620,2620
of:0000000000000008,2208,2208,2208,2208,2208,2208,2208,2208,2208,2208,...,2208,2208,2208,2208,2208,2208,2208,2208,2208,2208
of:0000000000000009,1752,1752,1752,1752,1752,1752,1752,1752,1752,1752,...,1752,1752,1752,1752,1752,1752,1752,1752,1752,1752
of:000000000000000a,5097,5097,5097,5097,5097,5097,5097,5097,5097,5097,...,5097,5097,5097,5097,5097,5097,5097,5097,5097,5097
of:000000000000000b,2476,2476,2476,2476,2476,2476,2476,2476,2476,2476,...,2476,2476,2476,2476,2476,2476,2476,2476,2476,2476
of:000000000000000c,5490,5490,5490,5490,5490,5490,5490,5490,5490,5490,...,5490,5490,5490,5490,5490,5490,5490,5490,5490,5490

In [15]:
df.groupby("Port Number").count()

,Switch ID,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Tx Dropped,Packets Rx Errors,Packets Tx Errors,Delta Received Packets,...,Total Load/Latest,Unknown Load/Rate,Unknown Load/Latest,Latest bytes counter,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Label,Binary Label
Port Number,,,,,,,,,,,,,,,,,,,,,
Port#:1,11903,11903,11903,11903,11903,11903,11903,11903,11903,11903,...,11903,11903,11903,11903,11903,11903,11903,11903,11903,11903
Port#:2,11846,11846,11846,11846,11846,11846,11846,11846,11846,11846,...,11846,11846,11846,11846,11846,11846,11846,11846,11846,11846
Port#:3,8961,8961,8961,8961,8961,8961,8961,8961,8961,8961,...,8961,8961,8961,8961,8961,8961,8961,8961,8961,8961
Port#:4,4701,4701,4701,4701,4701,4701,4701,4701,4701,4701,...,4701,4701,4701,4701,4701,4701,4701,4701,4701,4701

In [16]:
df.groupby("Label").count()

,Switch ID,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Tx Dropped,Packets Rx Errors,Packets Tx Errors,...,Total Load/Rate,Total Load/Latest,Unknown Load/Rate,Unknown Load/Latest,Latest bytes counter,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Binary Label
Label,,,,,,,,,,,,,,,,,,,,,
Blackhole,8420,8420,8420,8420,8420,8420,8420,8420,8420,8420,...,8420,8420,8420,8420,8420,8420,8420,8420,8420,8420
Diversion,5615,5615,5615,5615,5615,5615,5615,5615,5615,5615,...,5615,5615,5615,5615,5615,5615,5615,5615,5615,5615
Normal,3773,3773,3773,3773,3773,3773,3773,3773,3773,3773,...,3773,3773,3773,3773,3773,3773,3773,3773,3773,3773
Overflow,1022,1022,1022,1022,1022,1022,1022,1022,1022,1022,...,1022,1022,1022,1022,1022,1022,1022,1022,1022,1022
PortScan,9500,9500,9500,9500,9500,9500,9500,9500,9500,9500,...,9500,9500,9500,9500,9500,9500,9500,9500,9500,9500
TCP-SYN,9081,9081,9081,9081,9081,9081,9081,9081,9081,9081,...,9081,9081,9081,9081,9081,9081,9081,9081,9081,9081

In [17]:
df.groupby("Binary Label").count()

,Switch ID,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Packets Tx Dropped,Packets Rx Errors,Packets Tx Errors,...,Total Load/Rate,Total Load/Latest,Unknown Load/Rate,Unknown Load/Latest,Latest bytes counter,Table ID,Active Flow Entries,Packets Looked Up,Packets Matched,Label
Binary Label,,,,,,,,,,,,,,,,,,,,,
Attack,33638,33638,33638,33638,33638,33638,33638,33638,33638,33638,...,33638,33638,33638,33638,33638,33638,33638,33638,33638,33638
Normal,3773,3773,3773,3773,3773,3773,3773,3773,3773,3773,...,3773,3773,3773,3773,3773,3773,3773,3773,3773,3773

In [18]:
#Change all features (Switch ID, Port Number, Label, Binary Label) with string to integer to train machine learning models later
#Switch ID
switch_id_to_int = {"of:0000000000000001": 1, "of:0000000000000002": 2, "of:0000000000000003": 3, "of:0000000000000004": 4, "of:0000000000000005": 5, "of:0000000000000006": 6, "of:0000000000000007": 7, "of:0000000000000008": 8, "of:0000000000000009": 9, "of:000000000000000a": 10, "of:000000000000000b": 11, "of:000000000000000c": 12}
df["Switch ID"] = df["Switch ID"].map(switch_id_to_int)

#Port Number
port_number_to_int = {"Port#:1": 1, "Port#:2": 2, "Port#:3": 3,"Port#:4": 4}
df["Port Number"] = df["Port Number"].map(port_number_to_int)

#Label
label_to_int = {"Blackhole": 1, "Diversion": 2, "Normal": 3,"Overflow": 4, "PortScan": 5, "TCP-SYN": 6}
df["Label"] = df["Label"].map(label_to_int)

#Binary Label
binary_label_to_int = {"Attack": 1, "Normal": 2}
df["Binary Label"] = df["Binary Label"].map(binary_label_to_int)

In [19]:
#Delete all columns with values "0" only
df = df.loc[:, (df != 0).any(axis=0)]

In [20]:
#Delete all columns with negative values - some ML algorithms doesnt work with negative values
df=df[(df >= 0).all(1)]

In [21]:
#New Information about rows
#Before 37.411 rows and 34 columns
#After 
df.shape

(37176, 23)

In [22]:
df.count()

Switch ID                        37176
Port Number                      37176
Received Packets                 37176
Received Bytes                   37176
Sent Bytes                       37176
Sent Packets                     37176
Port alive Duration (S)          37176
Delta Received Packets           37176
Delta Received Bytes             37176
Delta Sent Bytes                 37176
Delta Sent Packets               37176
Delta Port alive Duration (S)    37176
Connection Point                 37176
Total Load/Rate                  37176
Total Load/Latest                37176
Unknown Load/Rate                37176
Unknown Load/Latest              37176
Latest bytes counter             37176
Active Flow Entries              37176
Packets Looked Up                37176
Packets Matched                  37176
Label                            37176
Binary Label                     37176
dtype: int64

In [23]:
df.head()

,Switch ID,Port Number,Received Packets,Received Bytes,Sent Bytes,Sent Packets,Port alive Duration (S),Delta Received Packets,Delta Received Bytes,Delta Sent Bytes,...,Total Load/Rate,Total Load/Latest,Unknown Load/Rate,Unknown Load/Latest,Latest bytes counter,Active Flow Entries,Packets Looked Up,Packets Matched,Label,Binary Label
0,12,1,132,9181,6311853,238,46,0,0,280,...,0,0,0,0,0,9,767,688,6,1
1,12,2,187,6304498,15713,171,46,146,5908166,5969,...,0,0,0,0,0,9,767,688,6,1
2,12,3,235,6311567,8030,58,46,2,278,280,...,0,0,0,0,0,9,767,688,6,1
3,12,4,59,7878,16439,182,46,2,278,280,...,0,0,0,0,0,9,767,688,6,1
4,10,1,188,6304547,16497,183,46,0,0,280,...,0,0,0,0,0,7,489,403,6,1

In [24]:
df.to_csv('UNR_IDD_cleaned.csv', index=False, header=True)